spring:
  # for tests
  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL10Dialect
  hbm2ddl:
    auto: create-drop
  show_sql: true

link:
  generator:
    hash:
      keys: 123, 234, 345
